version: '3'

services:
  tvti:
    container_name: tvti
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - bridge

networks:
  bridge:
    name: server-bridge
    external: true
